import { Router } from "express";
import { autenticarUsuario, selecionarEmpresa, exigirModulo, exigirPermissao } from "../../middlewares/auth.middleware.js";
import * as c from "./estoque.controller.js";
const r=Router();
r.use(autenticarUsuario, selecionarEmpresa, exigirModulo("ESTOQUE"));
r.get("/resumo", exigirPermissao("estoque.visualizar"), c.resumo);
r.get("/produtos", exigirPermissao("estoque.visualizar"), c.produtos);
r.get("/movimentacoes", exigirPermissao("estoque.visualizar"), c.movimentos);
r.get("/fornecedores", exigirPermissao("estoque.visualizar"), c.fornecedores);
r.post("/fornecedores", exigirPermissao("estoque.gerenciar"), c.criarFornecedor);
r.patch("/fornecedores/:id", exigirPermissao("estoque.gerenciar"), c.atualizarFornecedor);
r.get("/entradas", exigirPermissao("estoque.visualizar"), c.entradas);
r.post("/entradas", exigirPermissao("estoque.gerenciar"), c.criarEntrada);
r.post("/entradas/:id/cancelar", exigirPermissao("estoque.gerenciar"), c.cancelarEntrada);
r.post("/ajustes", exigirPermissao("estoque.gerenciar"), c.ajustar);
r.get("/inventarios", exigirPermissao("estoque.visualizar"), c.inventarios);
r.post("/inventarios", exigirPermissao("estoque.gerenciar"), c.criarInventario);
r.get("/inventarios/:id", exigirPermissao("estoque.visualizar"), c.inventario);
r.patch("/inventarios/:id/itens/:itemId", exigirPermissao("estoque.gerenciar"), c.contar);
r.post("/inventarios/:id/concluir", exigirPermissao("estoque.gerenciar"), c.concluir);
r.post("/inventarios/:id/cancelar", exigirPermissao("estoque.gerenciar"), c.cancelarInventario);
export default r;
