import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, HeartPulse, Scissors } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { api } from "../lib/api.js";

function isoFromLocal(v){return v?new Date(v).toISOString():null;}
export default function BookingPage(){const [params,setParams]=useSearchParams();const initial=params.get('tipo')==='BANHO_TOSA'?'BANHO_TOSA':'CONSULTORIO';const [type,setType]=useState(initial);const [petId,setPetId]=useState("");const [serviceId,setServiceId]=useState("");const [selected,setSelected]=useState([]);const [when,setWhen]=useState("");const [notes,setNotes]=useState("");const [payment,setPayment]=useState("PIX");const [result,setResult]=useState(null);const [error,setError]=useState("");const qc=useQueryClient();
 const pets=useQuery({queryKey:["portal-pets"],queryFn:async()=> (await api.get("/portal/pets")).data.dados});
 const services=useQuery({queryKey:["portal-servicos",type],queryFn:async()=> (await api.get(`/portal/servicos?tipo=${type}`)).data.itens});
 useEffect(()=>{setParams({tipo:type});setServiceId("");setSelected([]);setResult(null);setError("");},[type]);
 const total=useMemo(()=> (services.data||[]).filter(x=>selected.includes(x.id)).reduce((s,x)=>s+Number(x.precoVenda),0),[services.data,selected]);
 const booking=useMutation({mutationFn:async()=>{setError("");if(type==='CONSULTORIO')return (await api.post('/portal/agendamentos/consultorio',{petId,itemCatalogoId:serviceId,inicio:isoFromLocal(when),queixaPrincipal:notes})).data;return (await api.post('/portal/agendamentos/banho-tosa',{petId,itemCatalogoIds:selected,inicio:isoFromLocal(when),observacoesCliente:notes,formaPagamento:payment})).data;},onSuccess:data=>{setResult(data);qc.invalidateQueries({queryKey:["portal-agendamentos"]});},onError:e=>setError(e.response?.data?.message||"Não foi possível agendar.")});
 const approve=useMutation({mutationFn:()=>api.post(`/portal/pagamentos/${result.transaction.id}/simular-aprovacao`),onSuccess:()=>{setResult({...result,paid:true});qc.invalidateQueries({queryKey:["portal-agendamentos"]});}});
 function toggle(id){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
 return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">AGENDA ONLINE</p><h1>Agendar atendimento</h1><p>Escolha o pet, serviço e melhor horário.</p></div></div><div className="type-switch"><button className={type==='CONSULTORIO'?'active':''} onClick={()=>setType('CONSULTORIO')}><HeartPulse/>Consultório</button><button className={type==='BANHO_TOSA'?'active':''} onClick={()=>setType('BANHO_TOSA')}><Scissors/>Banho e Tosa</button></div>
 <section className="panel booking-panel">{error&&<div className="error-box">{error}</div>}{result?<div className="success-booking"><div className="success-icon">✓</div><h2>{type==='BANHO_TOSA'&&!result.paid?'Horário reservado!':'Agendamento confirmado!'}</h2>{type==='BANHO_TOSA'&&!result.paid?<><p>Para confirmar o Banho e Tosa, finalize o pagamento dentro do prazo da reserva.</p><div className="payment-summary"><CreditCard/><div><b>R$ {Number(result.transaction.valor).toFixed(2).replace('.',',')}</b><span>{result.transaction.forma} • {result.transaction.status}</span></div></div>{result.developmentSimulator&&<><div className="dev-note">Ambiente de desenvolvimento: nenhum pagamento real será cobrado.</div><button className="primary-button" onClick={()=>approve.mutate()} disabled={approve.isPending}>{approve.isPending?'Processando...':'Simular pagamento aprovado'}</button></>}</>:<p>Você pode acompanhar tudo em “Minha agenda”.</p>}<button className="ghost-button" onClick={()=>setResult(null)}>Fazer outro agendamento</button></div>:<div className="form-grid">
 <label>Pet<select value={petId} onChange={e=>setPetId(e.target.value)}><option value="">Selecione</option>{pets.data?.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label>Data e horário<input type="datetime-local" value={when} min={new Date(Date.now()+3600000).toISOString().slice(0,16)} onChange={e=>setWhen(e.target.value)}/></label>
 {type==='CONSULTORIO'?<label className="full">Serviço<select value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Selecione</option>{services.data?.map(s=><option key={s.id} value={s.id}>{s.nome} — R$ {Number(s.precoVenda).toFixed(2).replace('.',',')}</option>)}</select></label>:<div className="full"><span className="field-label">Serviços</span><div className="service-choice">{services.data?.map(s=><label key={s.id} className={selected.includes(s.id)?'selected':''}><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>toggle(s.id)}/><span><b>{s.nome}</b><small>{s.servico?.duracaoMinutos||60} min</small></span><em>R$ {Number(s.precoVenda).toFixed(2).replace('.',',')}</em></label>)}</div>{selected.length>0&&<div className="booking-total">Total <b>R$ {total.toFixed(2).replace('.',',')}</b></div>}</div>}
 <label className="full">Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={type==='CONSULTORIO'?'Conte brevemente o motivo da consulta':'Conte alguma necessidade especial do seu pet'}/></label>{type==='BANHO_TOSA'&&<label className="full">Forma de pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="PIX">PIX</option><option value="CARTAO">Cartão</option></select><small className="helper">O agendamento só é confirmado após o pagamento.</small></label>}
 <button className="primary-button full" disabled={!petId||!when||(type==='CONSULTORIO'?!serviceId:!selected.length)||booking.isPending} onClick={()=>booking.mutate()}>{booking.isPending?'Reservando...':type==='BANHO_TOSA'?'Reservar e pagar':'Confirmar agendamento'}</button></div>}</section></div>}
