import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, X } from "lucide-react";
import { api } from "../lib/api.js";

const empty={nome:"",especieId:"",racaId:"",sexo:"NAO_INFORMADO",dataNascimento:"",castrado:false,cor:"",alergias:"",observacoes:""};
export default function PetsPage(){const qc=useQueryClient();const [open,setOpen]=useState(false);const [form,setForm]=useState(empty);const [error,setError]=useState("");
 const pets=useQuery({queryKey:["portal-pets"],queryFn:async()=> (await api.get("/portal/pets")).data.dados});
 const catalogs=useQuery({queryKey:["portal-catalogos"],queryFn:async()=> (await api.get("/portal/catalogos")).data});
 const breeds=useMemo(()=> (catalogs.data?.racas||[]).filter(r=>r.especieId===form.especieId),[catalogs.data,form.especieId]);
 const create=useMutation({mutationFn:()=>api.post("/portal/pets",form),onSuccess:()=>{qc.invalidateQueries({queryKey:["portal-pets"]});setOpen(false);setForm(empty);},onError:e=>setError(e.response?.data?.message||"Erro ao cadastrar pet.")});
 return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">FAMÍLIA PET</p><h1>Meus pets</h1><p>Cadastre seus companheiros para agilizar os atendimentos.</p></div><button className="primary-button compact" onClick={()=>setOpen(true)}><Plus/>Adicionar pet</button></div>
 <div className="pet-grid">{pets.data?.map(p=><article className="pet-card" key={p.id}><div className="pet-avatar">{p.fotoUrl?<img src={p.fotoUrl}/>:p.nome[0]}</div><div><h3>{p.nome}</h3><p>{p.especie?.nome}{p.raca?.nome?` • ${p.raca.nome}`:""}</p><small>{p.pesos?.[0]?.peso?`${p.pesos[0].peso} kg`:"Peso não informado"}</small></div></article>)}</div>
 {open&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-title"><h2>Novo pet</h2><button onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="error-box">{error}</div>}<div className="form-grid"><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>Espécie<select value={form.especieId} onChange={e=>setForm({...form,especieId:e.target.value,racaId:""})}><option value="">Selecione</option>{catalogs.data?.especies?.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label>Raça<select value={form.racaId} onChange={e=>setForm({...form,racaId:e.target.value})}><option value="">Sem raça definida</option>{breeds.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label>Sexo<select value={form.sexo} onChange={e=>setForm({...form,sexo:e.target.value})}><option value="NAO_INFORMADO">Não informado</option><option value="MACHO">Macho</option><option value="FEMEA">Fêmea</option></select></label><label>Nascimento<input type="date" value={form.dataNascimento} onChange={e=>setForm({...form,dataNascimento:e.target.value})}/></label><label>Cor<input value={form.cor} onChange={e=>setForm({...form,cor:e.target.value})}/></label><label className="full">Alergias<textarea value={form.alergias} onChange={e=>setForm({...form,alergias:e.target.value})}/></label><label className="full">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label></div><div className="modal-actions"><button className="ghost-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button compact" onClick={()=>create.mutate()} disabled={!form.nome||!form.especieId||create.isPending}>Salvar pet</button></div></div></div>}
 </div>}
