import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, Building2, Check, ChevronLeft, CircleDollarSign, CreditCard, Edit3, FileText, Layers3, LoaderCircle, LogOut, Plus, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import BrandMark from "../components/BrandMark.jsx";
import Modal from "../components/Modal.jsx";
import api, { getApiErrorMessage } from "../lib/api.js";
import { formatCurrency, formatDate } from "../lib/formatters.js";
import { useAuth } from "../context/AuthContext.jsx";

const moduleLabels = { PDV:"PDV", ESTOQUE:"Estoque", CONSULTORIO:"Consultório", BANHO_TOSA:"Banho e Tosa", FINANCEIRO:"Financeiro", PORTAL_CLIENTE:"Portal do cliente", PONTO:"Ponto", FISCAL:"Fiscal", RELATORIOS:"Relatórios" };
const allModules = Object.keys(moduleLabels);
const statusLabels = { TRIAL:"Trial", ATIVA:"Ativa", INADIMPLENTE:"Inadimplente", SUSPENSA:"Suspensa", CANCELADA:"Cancelada", PENDENTE:"Pendente", PAGA:"Paga", VENCIDA:"Vencida" };

const emptyPlan = { slug:"", nome:"", descricao:"", precoMensal:0, precoAnual:0, trialDias:14, limiteEmpresas:1, limiteUsuarios:3, limiteClientes:1000, limitePets:1500, limiteFuncionarios:5, ativo:true, destaque:false, ordem:10, modulos:["PDV","ESTOQUE","BANHO_TOSA","PORTAL_CLIENTE","RELATORIOS"] };

function Metric({ icon:Icon, label, value, hint }) { return <article className="platform-metric"><span><Icon size={20}/></span><div><small>{label}</small><strong>{value}</strong>{hint && <em>{hint}</em>}</div></article>; }
function Status({ value }) { return <span className={`status-pill status-pill--${String(value||"").toLowerCase()}`}>{statusLabels[value]||value||"—"}</span>; }

export default function PlatformAdminPage() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const qc = useQueryClient();
  const [tab, setTab] = useState("PAINEL");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [planModal, setPlanModal] = useState(null);
  const [tenantModal, setTenantModal] = useState(null);
  const [invoiceModal, setInvoiceModal] = useState(false);

  const dashboard = useQuery({ queryKey:["platform-dashboard"], queryFn: async()=> (await api.get("/saas/plataforma/painel")).data.dados });
  const organizations = useQuery({ queryKey:["platform-orgs", search, status], queryFn: async()=> (await api.get("/saas/plataforma/organizacoes", { params:{ busca:search, status } })).data.dados || [] });
  const plans = useQuery({ queryKey:["platform-plans"], queryFn: async()=> (await api.get("/saas/plataforma/planos")).data.dados || [] });
  const invoices = useQuery({ queryKey:["platform-invoices"], queryFn: async()=> (await api.get("/saas/plataforma/faturas")).data.dados || [] });

  const refresh = async()=>{ await Promise.all([dashboard.refetch(), organizations.refetch(), plans.refetch(), invoices.refetch()]); };
  const mutateTenant = useMutation({ mutationFn: async({orgId,data})=>api.patch(`/saas/plataforma/organizacoes/${orgId}/assinatura`,data), onSuccess:()=>{setTenantModal(null);setError("");qc.invalidateQueries({queryKey:["platform-orgs"]});qc.invalidateQueries({queryKey:["platform-dashboard"]});}, onError:(e)=>setError(getApiErrorMessage(e)) });
  const savePlan = useMutation({ mutationFn: async({id,data})=> id ? api.patch(`/saas/plataforma/planos/${id}`,data) : api.post("/saas/plataforma/planos",data), onSuccess:()=>{setPlanModal(null);setError("");qc.invalidateQueries({queryKey:["platform-plans"]});}, onError:(e)=>setError(getApiErrorMessage(e)) });
  const payInvoice = useMutation({ mutationFn: async(id)=>api.post(`/saas/plataforma/faturas/${id}/pagar`), onSuccess:()=>{qc.invalidateQueries({queryKey:["platform-invoices"]});qc.invalidateQueries({queryKey:["platform-orgs"]});qc.invalidateQueries({queryKey:["platform-dashboard"]});}, onError:(e)=>setError(getApiErrorMessage(e)) });
  const cancelInvoice = useMutation({ mutationFn: async(id)=>api.post(`/saas/plataforma/faturas/${id}/cancelar`), onSuccess:()=>qc.invalidateQueries({queryKey:["platform-invoices"]}), onError:(e)=>setError(getApiErrorMessage(e)) });
  const createInvoice = useMutation({ mutationFn: async(data)=>api.post("/saas/plataforma/faturas",data), onSuccess:()=>{setInvoiceModal(false);qc.invalidateQueries({queryKey:["platform-invoices"]});qc.invalidateQueries({queryKey:["platform-dashboard"]});}, onError:(e)=>setError(getApiErrorMessage(e)) });

  const d = dashboard.data || {};
  const orgs = organizations.data || [];
  const planRows = plans.data || [];
  const invoiceRows = invoices.data || [];

  async function exit() { await logout(); navigate("/login", {replace:true}); }

  return <div className="platform-admin">
    <aside className="platform-sidebar"><BrandMark/><div className="platform-badge"><ShieldCheck size={16}/>Console interno</div><nav>{[["PAINEL",BarChart3,"Visão geral"],["ORGANIZACOES",Building2,"Organizações"],["PLANOS",Layers3,"Planos"],["FATURAS",CreditCard,"Faturas"]].map(([id,Icon,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><footer><div><strong>{user?.nome}</strong><span>{user?.email}</span></div><button className="icon-button" onClick={exit}><LogOut size={18}/></button></footer></aside>
    <main className="platform-main"><header className="platform-topbar"><div><span>Administração da plataforma</span><h1>{tab==="PAINEL"?"PetRise em números":tab==="ORGANIZACOES"?"Organizações e assinaturas":tab==="PLANOS"?"Planos comerciais":"Cobranças SaaS"}</h1></div><div><button className="ghost-button" onClick={()=>navigate("/selecionar-empresa")}><ChevronLeft size={16}/>Voltar aos tenants</button><button className="ghost-button" onClick={refresh}><RefreshCw size={16}/>Atualizar</button></div></header>
    {error && <div className="alert alert--error">{error}</div>}
    {tab === "PAINEL" && <div className="page-stack"><section className="platform-metrics"><Metric icon={Building2} label="Organizações" value={d.totalOrganizacoes||0}/><Metric icon={Sparkles} label="Em trial" value={d.trials||0}/><Metric icon={ShieldCheck} label="Assinaturas ativas" value={d.ativas||0}/><Metric icon={CircleDollarSign} label="MRR estimado" value={formatCurrency(d.mrr||0)} hint="Assinaturas mensais ativas"/><Metric icon={FileText} label="Faturas pendentes" value={d.faturasPendentes||0} hint={formatCurrency(d.valorPendente||0)}/></section><section className="panel"><div className="panel__heading"><div><span>Saúde da base</span><h2>Status das assinaturas</h2></div></div><div className="platform-status-grid">{[["Ativas",d.ativas,"ATIVA"],["Trials",d.trials,"TRIAL"],["Inadimplentes",d.inadimplentes,"INADIMPLENTE"],["Suspensas",d.suspensas,"SUSPENSA"]].map(([l,v,s])=><button key={s} onClick={()=>{setStatus(s);setTab("ORGANIZACOES")}}><Status value={s}/><strong>{v||0}</strong><span>{l}</span></button>)}</div></section><section className="panel"><div className="panel__heading"><div><span>Últimos cadastros</span><h2>Organizações recentes</h2></div></div><TenantTable rows={orgs.slice(0,8)} onEdit={setTenantModal}/></section></div>}
    {tab === "ORGANIZACOES" && <div className="page-stack"><section className="toolbar panel"><div className="search-field"><Search size={16}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar organização, slug ou empresa"/></div><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos os status</option>{["TRIAL","ATIVA","INADIMPLENTE","SUSPENSA","CANCELADA"].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></section><section className="panel"><TenantTable rows={orgs} onEdit={setTenantModal}/></section></div>}
    {tab === "PLANOS" && <div className="page-stack"><div className="page-actions"><button className="primary-button" onClick={()=>setPlanModal({...emptyPlan})}><Plus size={16}/>Novo plano</button></div><section className="platform-plan-grid">{planRows.map(plan=><article className="platform-plan-card" key={plan.id}><header><div><span>{plan.destaque?"Destaque":"Plano"}</span><h3>{plan.nome}</h3></div><button className="icon-button" onClick={()=>setPlanModal({...plan})}><Edit3 size={16}/></button></header><strong>{formatCurrency(plan.precoMensal)}<small>/mês</small></strong><p>{plan.descricao}</p><div className="platform-plan-modules">{plan.modulos.map(m=><span key={m}><Check size={12}/>{moduleLabels[m]||m}</span>)}</div><footer><span>{plan._count?.assinaturas||0} assinatura(s)</span><Status value={plan.ativo?"ATIVA":"CANCELADA"}/></footer></article>)}</section></div>}
    {tab === "FATURAS" && <div className="page-stack"><div className="page-actions"><button className="primary-button" onClick={()=>setInvoiceModal(true)}><Plus size={16}/>Fatura manual</button></div><section className="panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Organização</th><th>Descrição</th><th>Vencimento</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{invoiceRows.length?invoiceRows.map(f=><tr key={f.id}><td><strong>{f.organizacao?.nome||"—"}</strong></td><td>{f.descricao||"Assinatura PetRise"}</td><td>{formatDate(f.vencimento)}</td><td>{formatCurrency(f.valor)}</td><td><Status value={f.status}/></td><td><div className="row-actions">{["PENDENTE","VENCIDA"].includes(f.status)&&<button className="mini-button" onClick={()=>payInvoice.mutate(f.id)}>Marcar paga</button>}{f.status!=="PAGA"&&f.status!=="CANCELADA"&&<button className="mini-button mini-button--danger" onClick={()=>cancelInvoice.mutate(f.id)}>Cancelar</button>}</div></td></tr>):<tr><td className="empty-cell" colSpan="6">Nenhuma fatura.</td></tr>}</tbody></table></div></section></div>}
    </main>
    <PlanModal value={planModal} onClose={()=>setPlanModal(null)} onSave={(data)=>savePlan.mutate({id:planModal?.id,data})} loading={savePlan.isPending}/>
    <TenantModal value={tenantModal} plans={planRows} onClose={()=>setTenantModal(null)} onSave={(data)=>mutateTenant.mutate({orgId:tenantModal.id,data})} loading={mutateTenant.isPending}/>
    <InvoiceModal open={invoiceModal} organizations={orgs} plans={planRows} onClose={()=>setInvoiceModal(false)} onSave={(data)=>createInvoice.mutate(data)} loading={createInvoice.isPending}/>
  </div>;
}

function TenantTable({rows,onEdit}) { return <div className="table-scroll"><table className="data-table"><thead><tr><th>Organização</th><th>Plano</th><th>Status</th><th>Uso</th><th>Criada em</th><th></th></tr></thead><tbody>{rows.length?rows.map(org=><tr key={org.id}><td><strong>{org.configuracao?.nomeExibicao||org.nome}</strong><small className="table-subline">{org.slug} · {org.empresas?.[0]?.nomeFantasia||"Sem empresa"}</small></td><td>{org.assinaturaSaaS?.plano?.nome||"—"}</td><td><Status value={org.assinaturaSaaS?.status}/></td><td><span className="usage-inline"><Building2 size={13}/>{org._count?.empresas||0}<UsersRound size={13}/>{org._count?.usuarios||0}</span></td><td>{formatDate(org.createdAt)}</td><td><button className="icon-button" onClick={()=>onEdit(org)}><Settings2 size={16}/></button></td></tr>):<tr><td colSpan="6" className="empty-cell">Nenhuma organização encontrada.</td></tr>}</tbody></table></div>; }

function PlanModal({value,onClose,onSave,loading}) {
  if (!value) return null;
  return <PlanModalInner key={value.id || `new-${value.slug || "plan"}`} value={value} onClose={onClose} onSave={onSave} loading={loading}/>;
}
function PlanModalInner({value,onClose,onSave,loading}) {
  const [form,setForm] = useState(value);
  return <Modal open title={value.id?"Editar plano":"Novo plano"} subtitle="Defina preços, limites e módulos contratados." onClose={onClose} size="lg" footer={<><button className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={loading} onClick={()=>onSave(normalizePlan(form))}>{loading?"Salvando...":"Salvar plano"}</button></>}><PlanForm initial={value} onChange={setForm}/></Modal>;
}
function PlanForm({initial,onChange}) {
  const [f,setF]=useState(initial); function set(k,v){const n={...f,[k]:v};setF(n);onChange(n);} function toggle(m){set("modulos",f.modulos.includes(m)?f.modulos.filter(x=>x!==m):[...f.modulos,m]);}
  return <div className="form-grid form-grid--2"><label className="field"><span>Nome</span><input value={f.nome} onChange={e=>set("nome",e.target.value)}/></label><label className="field"><span>Slug</span><input value={f.slug} onChange={e=>set("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))}/></label><label className="field field--span-2"><span>Descrição</span><textarea value={f.descricao||""} onChange={e=>set("descricao",e.target.value)}/></label><label className="field"><span>Preço mensal</span><input type="number" step="0.01" value={f.precoMensal} onChange={e=>set("precoMensal",e.target.value)}/></label><label className="field"><span>Preço anual</span><input type="number" step="0.01" value={f.precoAnual} onChange={e=>set("precoAnual",e.target.value)}/></label><label className="field"><span>Trial (dias)</span><input type="number" value={f.trialDias} onChange={e=>set("trialDias",e.target.value)}/></label><label className="field"><span>Ordem</span><input type="number" value={f.ordem} onChange={e=>set("ordem",e.target.value)}/></label>{[["limiteEmpresas","CNPJs"],["limiteUsuarios","Usuários"],["limiteClientes","Clientes"],["limitePets","Pets"],["limiteFuncionarios","Funcionários"]].map(([k,l])=><label className="field" key={k}><span>Limite de {l}</span><input type="number" min="1" value={f[k]??""} onChange={e=>set(k,e.target.value)}/></label>)}<div className="field field--span-2"><span>Módulos</span><div className="module-check-grid">{allModules.map(m=><label key={m}><input type="checkbox" checked={f.modulos.includes(m)} onChange={()=>toggle(m)}/><span>{moduleLabels[m]}</span></label>)}</div></div><label className="check-row"><input type="checkbox" checked={Boolean(f.ativo)} onChange={e=>set("ativo",e.target.checked)}/>Plano ativo</label><label className="check-row"><input type="checkbox" checked={Boolean(f.destaque)} onChange={e=>set("destaque",e.target.checked)}/>Destacar no onboarding</label></div>;
}
function normalizePlan(f){const n={...f};["precoMensal","precoAnual","trialDias","ordem","limiteEmpresas","limiteUsuarios","limiteClientes","limitePets","limiteFuncionarios"].forEach(k=>{n[k]=n[k]===""?null:Number(n[k]);});n.trialDias=n.trialDias??0;n.ordem=n.ordem??0;return n;}

function TenantModal({value,plans,onClose,onSave,loading}) { if(!value)return null; return <TenantModalInner key={value.id} value={value} plans={plans} onClose={onClose} onSave={onSave} loading={loading}/>; }
function TenantModalInner({value,plans,onClose,onSave,loading}) { const a=value.assinaturaSaaS||{}; const [form,setForm]=useState({planoId:a.plano?.id||"",status:a.status||"TRIAL",ciclo:a.ciclo||"MENSAL",trialFimEm:a.trialFimEm?new Date(a.trialFimEm).toISOString().slice(0,16):"",proximaCobrancaEm:a.proximaCobrancaEm?new Date(a.proximaCobrancaEm).toISOString().slice(0,16):"",observacoesInternas:a.observacoesInternas||""}); const set=(k,v)=>setForm(f=>({...f,[k]:v})); return <Modal open title={value.nome} subtitle="Ajuste controlado da assinatura. Alterações ficam registradas no histórico SaaS." onClose={onClose} footer={<><button className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={loading} onClick={()=>onSave({...form,trialFimEm:form.trialFimEm?new Date(form.trialFimEm).toISOString():null,proximaCobrancaEm:form.proximaCobrancaEm?new Date(form.proximaCobrancaEm).toISOString():null})}>{loading?"Salvando...":"Salvar assinatura"}</button></>}><div className="form-grid form-grid--2"><label className="field"><span>Plano</span><select value={form.planoId} onChange={e=>set("planoId",e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>set("status",e.target.value)}>{["TRIAL","ATIVA","INADIMPLENTE","SUSPENSA","CANCELADA"].map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Ciclo</span><select value={form.ciclo} onChange={e=>set("ciclo",e.target.value)}><option>MENSAL</option><option>ANUAL</option></select></label><label className="field"><span>Fim do trial</span><input type="datetime-local" value={form.trialFimEm} onChange={e=>set("trialFimEm",e.target.value)}/></label><label className="field"><span>Próxima cobrança</span><input type="datetime-local" value={form.proximaCobrancaEm} onChange={e=>set("proximaCobrancaEm",e.target.value)}/></label><label className="field field--span-2"><span>Notas internas de suporte</span><textarea value={form.observacoesInternas} onChange={e=>set("observacoesInternas",e.target.value)} placeholder="Contexto de atendimento, exceções comerciais, contatos..."/></label></div></Modal>; }

function InvoiceModal({open,organizations,plans,onClose,onSave,loading}) { const [form,setForm]=useState({organizacaoId:"",valor:"",vencimento:new Date().toISOString().slice(0,10),descricao:"",planoDestinoId:"",ciclo:"MENSAL"}); if(!open)return null; const set=(k,v)=>setForm(f=>({...f,[k]:v})); return <Modal open title="Nova fatura manual" subtitle="Use para cobrança assistida, ajuste comercial ou regularização." onClose={onClose} footer={<><button className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={loading||!form.organizacaoId||!form.valor} onClick={()=>onSave({...form,valor:Number(form.valor),planoDestinoId:form.planoDestinoId||null})}>{loading?"Criando...":"Criar fatura"}</button></>}><div className="form-grid form-grid--2"><label className="field field--span-2"><span>Organização</span><select value={form.organizacaoId} onChange={e=>set("organizacaoId",e.target.value)}><option value="">Selecione</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select></label><label className="field"><span>Valor</span><input type="number" step="0.01" value={form.valor} onChange={e=>set("valor",e.target.value)}/></label><label className="field"><span>Vencimento</span><input type="date" value={form.vencimento} onChange={e=>set("vencimento",e.target.value)}/></label><label className="field"><span>Plano após pagamento (opcional)</span><select value={form.planoDestinoId} onChange={e=>set("planoDestinoId",e.target.value)}><option value="">Manter atual</option>{plans.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label className="field"><span>Ciclo</span><select value={form.ciclo} onChange={e=>set("ciclo",e.target.value)}><option>MENSAL</option><option>ANUAL</option></select></label><label className="field field--span-2"><span>Descrição</span><input value={form.descricao} onChange={e=>set("descricao",e.target.value)} placeholder="Cobrança manual PetRise"/></label></div></Modal>; }
